# Back/insight/migrations/0001_initial.py
# Generated by Django 4.2.20 on 2025-05-25 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InterestStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("stock_code", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "company_name")},
            },
        ),
        migrations.CreateModel(
            name="StockAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.TextField(blank=True)),
                ("keywords", models.JSONField(blank=True, default=list)),
                ("sentiment_stats", models.JSONField(blank=True, default=dict)),
                (
                    "task_status",
                    models.CharField(
                        choices=[
                            ("waiting", "대기"),
                            ("running", "진행"),
                            ("done", "완료"),
                            ("failed", "실패"),
                        ],
                        default="waiting",
                        max_length=10,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stock",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="insight.intereststock",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("sentiment", models.CharField(blank=True, max_length=10)),
                ("likes", models.PositiveIntegerField(default=0)),
                ("written_at", models.DateTimeField()),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="insight.stockanalysis",
                    ),
                ),
            ],
            options={
                "ordering": ["-likes"],
            },
        ),
    ]
