# insight/migrations/0002_stockanalysis_batch_ready.py
# Generated by Django 4.2.20 on 2025-05-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockanalysis',
            name='batch_ready',
            field=models.BooleanField(default=False),
        ),
    ]
