# financial_products/migrations/0002_alter_financialproduct_options_and_more.py
# Generated by Django 4.2.20 on 2025-05-27 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financial_products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialproduct',
            options={'ordering': ['dcls_month', 'bank__name', 'name'], 'verbose_name': '금융 상품', 'verbose_name_plural': '금융 상품 목록'},
        ),
        migrations.AlterModelOptions(
            name='joinedproduct',
            options={'ordering': ['-joined_at'], 'verbose_name': '가입 상품', 'verbose_name_plural': '가입 상품 목록'},
        ),
        migrations.AlterModelOptions(
            name='productoption',
            options={'ordering': ['product', 'save_trm', 'intr_rate_type', 'rsrv_type'], 'verbose_name': '상품 옵션', 'verbose_name_plural': '상품 옵션 목록'},
        ),
        migrations.AlterUniqueTogether(
            name='financialproduct',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='joinedproduct',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='productoption',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='financialproduct',
            name='dcls_end_day',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='공시 종료일'),
        ),
        migrations.AddField(
            model_name='financialproduct',
            name='dcls_month',
            field=models.CharField(max_length=6, null=True, verbose_name='공시월 (YYYYMM)'),
        ),
        migrations.AddField(
            model_name='financialproduct',
            name='dcls_strt_day',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='공시 시작일'),
        ),
        migrations.AddField(
            model_name='financialproduct',
            name='etc_note',
            field=models.TextField(blank=True, null=True, verbose_name='기타 유의사항'),
        ),
        migrations.AddField(
            model_name='financialproduct',
            name='fin_co_subm_day',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='금융회사 제출일'),
        ),
        migrations.AddField(
            model_name='financialproduct',
            name='fin_prdt_cd',
            field=models.CharField(default='UNKNOWN_PRODUCT_CODE', max_length=100, verbose_name='금융상품 코드'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financialproduct',
            name='join_deny',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='가입제한'),
        ),
        migrations.AddField(
            model_name='financialproduct',
            name='join_member',
            field=models.TextField(blank=True, null=True, verbose_name='가입 대상'),
        ),
        migrations.AddField(
            model_name='financialproduct',
            name='join_way',
            field=models.TextField(blank=True, null=True, verbose_name='가입 방법'),
        ),
        migrations.AddField(
            model_name='financialproduct',
            name='max_limit',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='최고 한도'),
        ),
        migrations.AddField(
            model_name='financialproduct',
            name='mtrt_int',
            field=models.TextField(blank=True, null=True, verbose_name='만기 후 이자율'),
        ),
        migrations.AddField(
            model_name='financialproduct',
            name='spcl_cnd',
            field=models.TextField(blank=True, null=True, verbose_name='우대 조건'),
        ),
        migrations.AddField(
            model_name='financialproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productoption',
            name='intr_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='저축 금리 (기본)'),
        ),
        migrations.AddField(
            model_name='productoption',
            name='intr_rate2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='최고 우대 금리'),
        ),
        migrations.AddField(
            model_name='productoption',
            name='intr_rate_type',
            field=models.CharField(choices=[('S', '단리'), ('M', '복리')], default='S', max_length=1, verbose_name='이자율 유형 코드'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productoption',
            name='intr_rate_type_nm',
            field=models.CharField(default='단리', max_length=10, verbose_name='이자율 유형명'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productoption',
            name='rsrv_type',
            field=models.CharField(blank=True, choices=[('S', '정액적립식'), ('F', '자유적립식')], max_length=1, null=True, verbose_name='적립 유형 코드'),
        ),
        migrations.AddField(
            model_name='productoption',
            name='rsrv_type_nm',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='적립 유형명'),
        ),
        migrations.AddField(
            model_name='productoption',
            name='save_trm',
            field=models.CharField(default='12', max_length=3, verbose_name='저축 기간 (개월)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bank',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='금융회사 코드'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(max_length=100, verbose_name='금융회사 명'),
        ),
        migrations.AlterField(
            model_name='financialproduct',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_products.bank', verbose_name='은행'),
        ),
        migrations.AlterField(
            model_name='financialproduct',
            name='name',
            field=models.CharField(max_length=255, verbose_name='금융상품명'),
        ),
        migrations.AlterField(
            model_name='financialproduct',
            name='product_type',
            field=models.CharField(choices=[('deposit', '정기예금'), ('saving', '적금')], max_length=10, verbose_name='상품 유형'),
        ),
        migrations.AlterField(
            model_name='joinedproduct',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='가입 금액'),
        ),
        migrations.AlterField(
            model_name='joinedproduct',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='가입일시'),
        ),
        migrations.AlterField(
            model_name='joinedproduct',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financial_products.productoption', verbose_name='선택 옵션'),
        ),
        migrations.AlterField(
            model_name='joinedproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_products.financialproduct', verbose_name='가입 상품'),
        ),
        migrations.AlterField(
            model_name='joinedproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_financial_products', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='financial_products.financialproduct', verbose_name='상품'),
        ),
        migrations.AlterUniqueTogether(
            name='financialproduct',
            unique_together={('fin_prdt_cd', 'dcls_month')},
        ),
        migrations.AlterUniqueTogether(
            name='joinedproduct',
            unique_together={('user', 'option')},
        ),
        migrations.AlterUniqueTogether(
            name='productoption',
            unique_together={('product', 'save_trm', 'intr_rate_type', 'rsrv_type')},
        ),
        migrations.RemoveField(
            model_name='financialproduct',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productoption',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='productoption',
            name='term_months',
        ),
    ]
