# Back/financial_products/migrations/0003_alter_productoption_save_trm.py
# Generated by Django 4.2.20 on 2025-05-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_products', '0002_alter_financialproduct_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoption',
            name='save_trm',
            field=models.PositiveSmallIntegerField(verbose_name='저축 기간 (개월)'),
        ),
    ]
