# Generated by Django 4.2.20 on 2025-05-28 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('branch_name', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': '은행 위치',
                'verbose_name_plural': '은행 위치 목록',
            },
        ),
        migrations.DeleteModel(
            name='BankBranch',
        ),
    ]
