# commodities/migrations/0002_alter_commodity_options_alter_pricehistory_options.py
# Generated by Django 4.2.20 on 2025-05-26 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commodity',
            options={'verbose_name': 'Commodity', 'verbose_name_plural': 'Commodities'},
        ),
        migrations.AlterModelOptions(
            name='pricehistory',
            options={'ordering': ['date'], 'verbose_name': 'Price history', 'verbose_name_plural': 'Price histories'},
        ),
    ]
