# back/accounts/migrations/0002_alter_customuser_social_login_type_and_more.py
# Generated by Django 4.2.20 on 2025-05-26 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='social_login_type',
            field=models.CharField(blank=True, choices=[('google', '구글'), ('kakao', '카카오'), ('naver', '네이버')], help_text='OAuth 공급자 타입', max_length=20),
        ),
        migrations.AlterField(
            model_name='pointtransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
